name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4.1.1
      
      - uses: pnpm/action-setup@v3.0.0
        with:
          version: 9.1.4

      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          cache: 'pnpm'

      - uses: actions/cache@v4.0.1
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format Check
        run: pnpm fmt:check
        
      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test